# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
 workflow_dispatch:
   inputs:
      newVersion:
        description: 'New Version'     
        required: true
      branch:
        description: 'Start Branch Name'     
        required: true
        default: develop
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "newVersion: ${{ github.event.inputs.newVersion }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 
          echo Add other actions to build,
          echo test, and deploy your project.
